### ISSUE TITLE
What's the meaning of compose files labels

### ISSUE THREAD

**Issue by qiuyimo** [khs1994-docker/lnmp#282]
### 操作系统

* [x] macOS

### Docker 版本

* [x] Stable (v17.12)
### 问题描述

docker-compose.yml 文件中

```yaml
services:

  mysql:
    << : *default-common
    image: "${LNMP_SELF_BUILD_DOCKER_IMAGE_PREFIX:-khs1994}/mysql:${KHS1994_LNMP_MYSQL_VERSION:-8.0.3}"
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: test
      # MYSQL_USER:
      # MYSQL_PASSWORD:
    ports:
      - "${MYSQL_PORT:-127.0.0.1:3306}:3306"
    volumes:
      - ./config/mysql/conf.d/${MYSQL_CONF:-docker.cnf}:/etc/mysql/conf.d/docker.cnfro
      # https://github.com/docker-library/docs/tree/master/mysql#initializing-a-fresh-instance
      - ./backup/init:/docker-entrypoint-initdb.d:ro
      - mysql-data:/var/lib/mysql:rw
      - ./logs/mysql:/var/log/mysql:rw
      - ./backup/mysql:/backup:rw
    command:
      - mysqld
      - --character-set-server=utf8mb4
    secrets:
      - db_root_password
    labels:
      - ${LNMP_DOMAIN:-com.khs1994.lnmp}.mysql=true
```

其中的 labels 的key, 默认值是 `com.khs1994.lnmp.mysql`, 这个是什么意思? 

我查看资料, 有的举例子用的是: 

```yaml
version: "3"
services:
  web:
    image: web
    labels:
      com.example.description: "This label will appear on all containers for the web service"
```
这里用的是 `com.example.description`.

这个 `com` 开头的字符串. 是什么? 作用是什么? 是什么语法? 

问的比较基础, 查资料无从下手, 请见谅.
