### ISSUE TITLE
docker-compose 中的 TZ 环境变量是如何传递的?

### ISSUE THREAD

**Issue by qiuyimo** [khs1994-docker/lnmp#285]
### 操作系统

* [x] macOS
### Docker 版本

* [x] Stable (v17.12)

### 问题描述
docker-compose 中的 TZ 环境变量是如何传递的?

```yaml
  nginx:
    depends_on:
    - php7
    environment:
      TZ: Asia/Shanghai
```

这个环境变量TZ, 我知道是设置时区, 但是我不理解是怎么传递进去的? 官方的基础镜像是怎么使用的? 

还是我理解错了? 看了 hub 上的官方基础镜像, 没找到哪里给提示了. 

类似的环境变量还有哪些? 怎么知道官方的基础镜像哪些是可以设置的?

**Comment by khs1994** [comment]
环境变量随便设，和 Linux 环境变量一个意思，具体怎么实现的你先不用管，你现在只要知道

在这里设置了某某选项，容器中是什么结果就行

```yaml
  nginx:
    depends_on:
    - php7
    environment:
      a: 1
```

启动容器

```bash
$ docker exec -it ...

$ env

...
a=1
...

```
