### ISSUE TITLE
volumes 中 type: bind 与 HOST:CONTAINER:ro 的区别? 如何把默认的配置映射到主机目录?

### ISSUE THREAD

**Issue by qiuyimo** [khs1994-docker/lnmp#289]
### 操作系统

* [x] macOS

### Docker 版本

* [x] Stable (v17.12)

### 问题描述
```yaml
    volumes:
      # - ./config/nginx:/etc/nginx/conf.d:ro
      - type: bind
        source: ./config/${NGINX_CONF_D:-nginx}
        target: /etc/nginx/conf.d
      - ./app:${LNMP_PHP_PATH:-/app}
      - ./config/etc/nginx/${NGINX_CONF:-nginx.conf}:/etc/nginx/nginx.conf:ro
      - ./logs/nginx:/var/log/nginx:rw
```

#### 问题1

`type: bind` 这中写法, 和 `HOST:CONTAINER:ro` 这种方式, 有什么区别? 为什么要这么写啊? 翻文档. 还是不懂. 

#### 问题2

nginx 的配置如何能自动的写入到映射的主机目录中. 

例如: nginx 在容器中默认的配置文件, 如何能映射到主机的目录中?
