### ISSUE TITLE
Some questions about building your own mirror

### ISSUE THREAD

**Issue by lichnow** [khs1994-docker/lnmp#611]
比如,在`dockerfile`中的`Nginx`的`docker-compose.yml`配置如下
```
version: '3.7'
services:

  alpine:
    build:
      context: ./alpine
      args:
        # OPENSSL_BRANCH: master
        NGINX_VERSION: ${NGINX_VERSION:-1.15.6}
        ALPINE_URL: mirrors.ustc.edu.cn # dl-cdn.alpinelinux.org
        OPENSSL_URL: https://gitee.com/mirrors/openssl.git
    image: khs1994/nginx:${NGINX_VERSION:-1.15.6}-alpine
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./app:/app/test:rw
```
在`根目录`下的`compose-docker.yml`内容如下
```
nginx:
    << : *default-common
    image: "${LNMP_SELF_BUILD_DOCKER_IMAGE_PREFIX:-khs1994}/nginx:${LNMP_NGINX_VERSION:-1.15.6}-alpine"
    ports:
      - "${LNMP_NGINX_HTTPS_PORT:-0.0.0.0:443}:443"
      - "${LNMP_NGINX_HTTP_PORT:-0.0.0.0:80}:80"
    volumes:
      # - ./config/nginx:/etc/nginx/conf.d:ro,cached
      - type: bind
        source: ./config/${LNMP_NGINX_CONF_D:-nginx}
        target: /etc/nginx/conf.d
      - ${APP_ROOT:-./app}:${LNMP_PHP_PATH:-/app}:cached
      - ./config/etc/nginx/${LNMP_NGINX_CONF:-nginx.conf}:/etc/nginx/nginx.conf:ro,cached
      - ./log/nginx:/var/log/nginx:delegated
    working_dir: /app
    networks:
      - frontend
    depends_on:
      - php7
```
#### 问题一
现在我在`.env`配置文件里把`LNMP_SELF_BUILD_DOCKER_IMAGE_PREFIX`改成了`myNginx`,不过`./lnmp-docker up`的时候说这个镜像不存在。`myNginx/nginx:1.15.6-alpine`这个镜像。是不是要自定义镜像需要先修改`dockerfile/nginx/docker-compose.yml`这个文件,然后在这个目录里`docker-compose  build`,接着`push`到`docker官方仓库`才能使用吗？

#### 问题二
`dockerfile/nginx/docker-compose.yml`这个文件里面的`image: khs1994/nginx:${NGINX_VERSION:-1.15.6}-alpine`这个镜像,是你push到docker官方仓库的吗？我需要把这个镜像名称也改掉,请问这个镜像怎么改？

还是新手，对这些流程并不是很清楚,望指点^V^
