### ISSUE TITLE
What's this for?

### ISSUE THREAD

**Issue by lichnow** [khs1994-docker/lnmp#612]
尝试自行构建镜像，发现一个`nightly-fpm-alpine`的配置
```
nightly:
    build:
      context: ./nightly/alpine
      args:
        PHP_VERSION: nightly
        ALPINE_URL: mirrors.ustc.edu.cn
      target: php
    image: ${DOCKER_HUB_USERNAME:-khs1994}/php:nightly-fpm-alpine
```
这个php的版本用来干嘛的？

还有一个问题`checkout 18.0.9`之后发现配置php的`dockerfile`里面的`composer`配置不见了，取而代之的是新建了一个专门用于构建`composer`的镜像，然而php配置根目录里并没有包含`composer`镜像的服务配置,在`php/72/alpine/dockerfile-compose.yml`里面也没有配置,那`composer`镜像怎么构建呢?同理还有`supervisord`
