### ISSUE TITLE
Supervisor mirroring cannot manage multiple environments

### ISSUE THREAD

**Issue by lichnow** [khs1994-docker/lnmp#625]
现在lnmp包里的supervisor镜像因为继承了php-fpm的镜像所以只能管理php进程,无法运行Node命令,也无法运行ruby等其它环境。请教一下，如何能使supervisor运行任意环境？
我现在的办法是复制一遍Node环境的dockerfile放到supervisor的dockerfile里面，虽然可以使用，但是感觉并不是很好,能有什么办法，使node，ruby或者其它任意环境以镜像的方式一起合并到supervisor里面吗？

**Comment by khs1994** [comment]
不要把容器当作虚拟机。

一个容器中运行的进程尽可能单一。

**Comment by lichnow** [comment]
@khs1994 那具体现在需要在supervisor里运行node和php,是需要开两个supervisor吗？还是怎么操作？因为一个要运行socket.js一个运行laravel的任务列队

**Comment by lichnow** [comment]
我现在改成这样
```
supervisord:
    << : *php7
    networks:
      - backend
    image: "gkrio/php:supervisord"
    # secrets:
    #   - source: supervisord_ini
    #     target: /etc/supervisord.ini
    volumes:
      - type: bind
        source: ./config/supervisor/php
        target: /etc/supervisor/conf.d
      - ./log/supervisor/php:/var/log/supervisor:delegated
      - ${APP_ROOT:-./app}:${LNMP_PHP_PATH:-/app}:cached
      # - ./config/etc/supervisor/supervisord.conf:/etc/supervisor/supervisord.conf:ro,cached
    command: ["/usr/bin/supervisord","-n","-c","/etc/supervisor/supervisord.conf"]
    expose:
      - "9001"

  supervisord-node:
    networks:
      - backend
    image: "gkrio/node:supervisord"
    volumes:
      - type: bind
        source: ./config/supervisor/node
        target: /etc/supervisor/conf.d
      - ./log/supervisor/node:/var/log/supervisor:delegated
      - ${APP_ROOT:-./app}:${LNMP_PHP_PATH:-/app}:cached
    command: ["/usr/bin/supervisord","-n","-c","/etc/supervisor/supervisord.conf"]
```
docker镜像for node
```
FROM gkrio/node:latest

FROM gkrio/php:${PHP_VERSION}

RUN apk update && apk add --no-cache supervisor \
    && mkdir -p /etc/supervisor/conf.d/ \
    && mkdir -p /var/log/supervisor/

COPY supervisord.conf /etc/supervisor/supervisord.conf

VOLUME ["/etc/supervisor/conf.d"]

CMD ["/usr/bin/supervisord","-n","-c","/etc/supervisor/supervisord.conf"]
```
php类似，这样的方式是正确合理的吗？
