### ISSUE TITLE
The role of nightly as the main branch

### ISSUE THREAD

**Issue by lichnow** [khs1994-docker/lnmp#626]
前面你说过`nightly`是作为php-fpm的主分支，但是具体作用并不是很懂，我看到docker-lnmp包里大部分都是用到7.2.12或者其它的版本分支,nightly这个Master分支的作用是什么？与7.2.12等版本分支的差别在哪里？具体用在哪里呢？

**Comment by khs1994** [comment]
php 源码使用 git 管理。

* https://github.com/php/php-src

nightly 编译 master 分支。

为的是体验最新的功能。

**Comment by lichnow** [comment]
看了一下`.travis.yml`，里面不仅写进去了composer,supervisor,unit这些，还把每个版本也写进去了，那么我直接使用`travis`构建成功了，`docker-compose.yml`这个本地构建后再push的东西就基本没用，不用去管了呢

**Comment by khs1994** [comment]
docker-compose 是为了本地测试，一般镜像构建都在 CI 上完成。

**Comment by lichnow** [comment]
@khs1994 travis一直无法构建，出现`!`,日志太长无法查看错误，具体是什么原因呢？如图
![](http://static.phpna.com/images/20181130114131.png)
我配置如下
```
language: bash

sudo: required

os: linux
dist: xenial

services:
- docker

before_install:
# 升级 Docker 最新 stable
- docker --version
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) ${DOCKER_CHANNEL}"
- sudo apt-get update
- sudo apt-get -y install docker-ce
- docker --version
# 升级最新 Docker Compose
- docker-compose --version
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- docker-compose --version
# ubuntu 14.04
# - echo 'DOCKER_OPTS="--experimental"' | sudo tee /etc/default/docker
# - sudo service docker restart
# ubuntu 16.04
- sudo mkdir -p /etc/systemd/system/docker.service.d
- echo -e '[Service]\nExecStart=\nExecStart=/usr/bin/dockerd' | sudo tee /etc/systemd/system/docker.service.d/docker.conf
- echo '{"hosts":["unix:///var/run/docker.sock","tcp://0.0.0.0:2375"],"experimental":true}' | sudo tee /etc/docker/daemon.json
- sudo systemctl daemon-reload
- sudo systemctl cat docker
- sudo systemctl restart docker

script:
  - cp .env.example .env
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # - docker-compose build ${PHP_VERSION}
  - if [ -n "$UNIT" ];then docker build --target=php -t $DOCKER_HUB_ORGANIZTION/php:${PHP_TAG_VERSION}-unit-alpine ${FOLDER}; fi
  - if [ -n "$SUPERVISOR" ];then docker build -t $DOCKER_HUB_ORGANIZTION/php:${PHP_TAG_VERSION}-supervisor-alpine ${FOLDER}; fi
  - if [ -n "$COMPOSER" ];then docker build -t $DOCKER_HUB_ORGANIZTION/php:${PHP_TAG_VERSION}-composer-alpine ${FOLDER}; fi
  - if [ -n "$ALPINE" ];then docker build --target=php -t $DOCKER_HUB_ORGANIZTION/php:${PHP_TAG_VERSION}-alpine ${FOLDER}; fi

after_success:
  - if [ -n "$UNIT" ];then docker push $DOCKER_HUB_ORGANIZTION/php:${PHP_TAG_VERSION}-unit-alpine; fi
  - if [ -n "$SUPERVISOR" ];then docker push $DOCKER_HUB_ORGANIZTION/php:${PHP_TAG_VERSION}-supervisor-alpine; fi
  - if [ -n "$COMPOSER" ];then docker push $DOCKER_HUB_ORGANIZTION/php:${PHP_TAG_VERSION}-composer-alpine; fi
  - if [ -n "$ALPINE" ];then docker-compose push ${PHP_VERSION}; fi
  - curl -X POST https://hooks.microbadger.com/images/$DOCKER_HUB_ORGANIZTION/php/OMVCEKSr9I0cjhU0DQop3HwjYAc=

branches:
  only:
  - master
  # - dev

env:
  matrix:
  - PHP_VERSION=5_6_X FOLDER=5.6 PHP_TAG_VERSION=5.6.38 ALPINE=1
  - PHP_VERSION=7_2_X FOLDER=7.2 PHP_TAG_VERSION=7.2.12 ALPINE=1
  - PHP_VERSION=7_2_X FOLDER=unit  PHP_TAG_VERSION=7.2.12 UNIT=1
  - PHP_VERSION=7_2_X FOLDER=supervisor PHP_TAG_VERSION=7.2.12 SUPERVISOR=1
  - PHP_VERSION=7_2_X FOLDER=composer PHP_TAG_VERSION=7.2.12 COMPOSER=1
  - PHP_VERSION=nightly FOLDER=nightly PHP_TAG_VERSION=nightly ALPINE=1
  global:
  - DOCKER_COMPOSE_VERSION=1.22.0
  - DOCKER_BUILDKIT=1
  - DOCKER_CHANNEL=stable
  - DOCKER_HUB_ORGANIZTION=gkrio

matrix:
  fast_finish: true
  allow_failures:
  - env: PHP_VERSION=nightly FOLDER=nightly PHP_TAG_VERSION=nightly
```
代码仓库
[https://github.com/gkr-repo/php](https://github.com/gkr-repo/php)
基本没改什么东西，就是一直出现`!`，我把其它都注释，只构建`7.2.12`也不行
